### ISSUE TITLE
Disgusting

### ISSUE THREAD

**Issue by Vincent2212** [ankitjosh78/hang-movie-man#1]
Not putting spaces when assigning variables.

**Comment by ankitjosh78** [comment]
> Not putting spaces when assigning variables.

Hey thanks for reminding me, I was going to organize the code and do a refractor soon.

**Comment by ankitjosh78** [comment]
Check the latest commit.

**Comment by ankitjosh78** [comment]
Check the latest commit.

**Comment by Vincent2212** [comment]
Haha! I was messing with you! Pretty fun project though.

**Comment by ankitjosh78** [comment]
> Haha! I was messing with you! Pretty fun project though.

Yeah lol I figured that out 😂
